services:
  - type: web
    name: progress-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    disk:
      name: database
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
